### ISSUE TITLE
Needs a demo/sample application

### ISSUE THREAD

**Issue by mattpage** [jivesoftware/react-d3-charts#2]
It's not immediately obvious how to use this. A demo/sample app would be helpful.

**Comment by toddlemoine** [comment]
I'll take this. I got this. I know kung fu.

**Comment by mattpage** [comment]
Hey, I needed some visual feedback for recent changes, so I created a demo branch.

**Comment by mattpage** [comment]
I think this issue is pretty much resolved by the /demo that is now in-place.
@toddlemoine pull the latest, npm install, and then npm run demo.
Let me know what you think or feel free to make any modifications.
